import re
import base64
import secrets

KEYWORDS = {"and","break","do","else","elseif","end","false","for","function","if",
"in","local","nil","not","or","repeat","return","then","true","until","while",
"continue","type","export"}

PROTECTED = {"game","workspace","script","shared","plugin","_G","_ENV","math",
"string","table","task","coroutine","debug","os","utf8","pairs","ipairs","next",
"select","pcall","xpcall","require","print","warn","error","assert","tonumber",
"tostring","type","typeof","setmetatable","getmetatable","rawget","rawset",
"rawequal","rawlen","unpack","Instance","Enum","Vector2","Vector3","CFrame",
"Color3","UDim","UDim2","RaycastParams","TweenInfo","BrickColor","Random",
"DateTime","bit32","buffer"}

TOKEN_RE = re.compile(
    r'(?P<comment>--\[(?:=*)\[[\s\S]*?\](?:=*)\]|--[^\n]*)'
    r'|(?P<string>"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\')'
    r'|(?P<number>\b\d+(?:\.\d+)?\b)'
    r'|(?P<ident>[A-Za-z_][A-Za-z0-9_]*)'
    r'|(?P<space>\s+)'
    r'|(?P<other>.)', re.MULTILINE)

def _safe_name():
    return "_L" + secrets.token_hex(4)

def _encode_string(raw, decoder):
    if len(raw) < 2 or raw[0] not in "\"'" or raw[-1] != raw[0]:
        return raw
    payload = base64.b64encode(raw[1:-1].encode("utf-8")).decode("ascii")
    return f'{decoder}("{payload}")'

def obfuscate(source):
    decoder = "_D" + secrets.token_hex(4)
    tokens = []
    for m in TOKEN_RE.finditer(source):
        if m.lastgroup != "comment":
            tokens.append([m.lastgroup, m.group(0)])

    names = {}
    for i, (kind, value) in enumerate(tokens):
        if kind == "ident" and value == "local":
            j = i + 1
            if j < len(tokens) and tokens[j][1] == "function":
                j += 1
            if j < len(tokens) and tokens[j][0] == "ident":
                old = tokens[j][1]
                if old not in KEYWORDS and old not in PROTECTED:
                    names.setdefault(old, _safe_name())

    out, prev = [], None
    for kind, value in tokens:
        if kind == "ident" and value in names and prev not in {".", ":"}:
            value = names[value]
        elif kind == "string":
            value = _encode_string(value, decoder)
        elif kind == "number" and "." not in value:
            n = int(value)
            if n >= 2:
                a = secrets.randbelow(n - 1) + 1
                value = f"({a}+{n-a})"
        out.append(value)
        if kind != "space":
            prev = value

    prefix = """-- Generated by Luau Obfuscator
local DECODER = function(s)
    local b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    s=s:gsub("[^"..b.."=]","")
    return (s:gsub(".", function(x)
        if x=="=" then return "" end
        local r,f="",(b:find(x,1,true)-1)
        for i=6,1,-1 do r=r..((f%2^i-f%2^(i-1)>0) and "1" or "0") end
        return r
    end)):gsub("%d%d%d?%d?%d?%d?%d?%d?", function(x)
        if #x~=8 then return "" end
        local c=0
        for i=1,8 do c=c+(x:sub(i,i)=="1" and 2^(8-i) or 0) end
        return string.char(c)
    end)
end

"""
    prefix = prefix.replace("DECODER", decoder, 1)
    return prefix + "".join(out).strip() + "\n"
